# Generated by Django 2.0.1 on 2018-02-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upudated',
            new_name='updated',
        ),
    ]
